Return-Path: <stable-owner@vger.kernel.org>
X-Original-To: lists+stable@lfdr.de
Delivered-To: lists+stable@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id E85FD53A9EE
	for <lists+stable@lfdr.de>; Wed,  1 Jun 2022 17:26:52 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1355398AbiFAP0f (ORCPT <rfc822;lists+stable@lfdr.de>);
        Wed, 1 Jun 2022 11:26:35 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:40572 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S1355401AbiFAP0e (ORCPT
        <rfc822;stable@vger.kernel.org>); Wed, 1 Jun 2022 11:26:34 -0400
Received: from ams.source.kernel.org (ams.source.kernel.org [IPv6:2604:1380:4601:e00::1])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id 6CED49C2E3;
        Wed,  1 Jun 2022 08:26:33 -0700 (PDT)
Received: from smtp.kernel.org (relay.kernel.org [52.25.139.140])
        (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
        (No client certificate requested)
        by ams.source.kernel.org (Postfix) with ESMTPS id 21EE2B81AE1;
        Wed,  1 Jun 2022 15:26:32 +0000 (UTC)
Received: by smtp.kernel.org (Postfix) with ESMTPSA id A678CC385B8;
        Wed,  1 Jun 2022 15:26:30 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=kernel.org;
        s=k20201202; t=1654097190;
        bh=+lhyoETMxQ8u9dpTirla7kouIoEKqFSNKpqd3SUO8vI=;
        h=Date:From:To:Cc:Subject:In-Reply-To:References:From;
        b=gWKhHwcVtjxU+xiAUHYPfFRk+fFgiKeKZ4p00Onisjo5Md4W1fcO7QFHQg7H5g8oc
         LCWxt//j3Hqcz7EhQARfjDgxfsMJwD35KRnQK09qWNo9SPhErYPqc1sQ8iKv4+0PHa
         AQNV00G4CIHiFeF1YK6Vx8DvnbuQuorpYLocjslCXl8em835vSWxw9LZK9P3PLM2bH
         SISfiG91au87kIGRaX19RQ9Izm+Zm1/1WX6z+0tugmIvGBr7D6RGk1xX0XX9Pc71wo
         VrpYrNtbBGXrMFf3/uQkquIt3eCCgS0JOW75oycP192eC22AbEa3Wa2uWL8Qt6VxiA
         Fr+vO9z9TPWVw==
Received: from sofa.misterjones.org ([185.219.108.64] helo=why.misterjones.org)
        by disco-boy.misterjones.org with esmtpsa  (TLS1.3) tls TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        (Exim 4.94.2)
        (envelope-from <maz@kernel.org>)
        id 1nwQEu-00F1H5-5H; Wed, 01 Jun 2022 16:26:28 +0100
Date:   Wed, 01 Jun 2022 16:26:27 +0100
Message-ID: <877d605rrw.wl-maz@kernel.org>
From:   Marc Zyngier <maz@kernel.org>
To:     Sasha Levin <sashal@kernel.org>
Cc:     linux-kernel@vger.kernel.org, stable@vger.kernel.org,
        Joey Gouly <joey.gouly@arm.com>,
        Catalin Marinas <catalin.marinas@arm.com>, will@kernel.org,
        broonie@kernel.org, alexandru.elisei@arm.com, mark.rutland@arm.com,
        linux-arm-kernel@lists.infradead.org
Subject: Re: [PATCH AUTOSEL 5.18 15/49] arm64: Expand ESR_ELx_WFx_ISS_TI to match its ARMv8.7 definition
In-Reply-To: <20220601135214.2002647-15-sashal@kernel.org>
References: <20220601135214.2002647-1-sashal@kernel.org>
        <20220601135214.2002647-15-sashal@kernel.org>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI-EPG/1.14.7 (Harue)
 FLIM-LB/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL-LB/10.8 EasyPG/1.0.0 Emacs/27.1
 (x86_64-pc-linux-gnu) MULE/6.0 (HANACHIRUSATO)
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
Content-Type: text/plain; charset=US-ASCII
X-SA-Exim-Connect-IP: 185.219.108.64
X-SA-Exim-Rcpt-To: sashal@kernel.org, linux-kernel@vger.kernel.org, stable@vger.kernel.org, joey.gouly@arm.com, catalin.marinas@arm.com, will@kernel.org, broonie@kernel.org, alexandru.elisei@arm.com, mark.rutland@arm.com, linux-arm-kernel@lists.infradead.org
X-SA-Exim-Mail-From: maz@kernel.org
X-SA-Exim-Scanned: No (on disco-boy.misterjones.org); SAEximRunCond expanded to false
X-Spam-Status: No, score=-7.7 required=5.0 tests=BAYES_00,DKIMWL_WL_HIGH,
        DKIM_SIGNED,DKIM_VALID,DKIM_VALID_AU,DKIM_VALID_EF,RCVD_IN_DNSWL_HI,
        SPF_HELO_NONE,SPF_PASS,T_SCC_BODY_TEXT_LINE autolearn=ham
        autolearn_force=no version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <stable.vger.kernel.org>
X-Mailing-List: stable@vger.kernel.org

On Wed, 01 Jun 2022 14:51:39 +0100,
Sasha Levin <sashal@kernel.org> wrote:
> 
> From: Marc Zyngier <maz@kernel.org>
> 
> [ Upstream commit 6a437208cb942a2dd98f7e1c3fd347ed3d425ffc ]
> 
> Starting with FEAT_WFXT in ARMv8.7, the TI field in the ISS
> that is reported on a WFx trap is expanded by one bit to
> allow the description of WFET and WFIT.
> 
> Special care is taken to exclude the WFxT bit from the mask
> used to match WFI so that it also matches WFIT when trapped from
> EL0.
> 
> Reviewed-by: Joey Gouly <joey.gouly@arm.com>
> Signed-off-by: Marc Zyngier <maz@kernel.org>
> Acked-by: Catalin Marinas <catalin.marinas@arm.com>
> Link: https://lore.kernel.org/r/20220419182755.601427-2-maz@kernel.org
> Signed-off-by: Sasha Levin <sashal@kernel.org>

Please do not backport this patch. It achieves nothing on its own, and
the kernel isn't broken without it.

Also, please do not AUTOSEL KVM/arm64 patches that are not tagged with
a Cc stable.

Thanks,

	M.

-- 
Without deviation from the norm, progress is not possible.
