Return-Path: <stable-owner@vger.kernel.org>
X-Original-To: lists+stable@lfdr.de
Delivered-To: lists+stable@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [23.128.96.18])
	by mail.lfdr.de (Postfix) with ESMTP id 33CBD377D4B
	for <lists+stable@lfdr.de>; Mon, 10 May 2021 09:40:04 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S230137AbhEJHlH (ORCPT <rfc822;lists+stable@lfdr.de>);
        Mon, 10 May 2021 03:41:07 -0400
Received: from mail.kernel.org ([198.145.29.99]:49650 "EHLO mail.kernel.org"
        rhost-flags-OK-OK-OK-OK) by vger.kernel.org with ESMTP
        id S230001AbhEJHlG (ORCPT <rfc822;stable@vger.kernel.org>);
        Mon, 10 May 2021 03:41:06 -0400
Received: from disco-boy.misterjones.org (disco-boy.misterjones.org [51.254.78.96])
        (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
        (No client certificate requested)
        by mail.kernel.org (Postfix) with ESMTPSA id 761426128E;
        Mon, 10 May 2021 07:40:02 +0000 (UTC)
Received: from 78.163-31-62.static.virginmediabusiness.co.uk ([62.31.163.78] helo=why.misterjones.org)
        by disco-boy.misterjones.org with esmtpsa  (TLS1.3) tls TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        (Exim 4.94.2)
        (envelope-from <maz@kernel.org>)
        id 1lg0WG-000JiN-9o; Mon, 10 May 2021 08:40:00 +0100
Date:   Mon, 10 May 2021 08:39:59 +0100
Message-ID: <8735uvox4g.wl-maz@kernel.org>
From:   Marc Zyngier <maz@kernel.org>
To:     Shaokun Zhang <zhangshaokun@hisilicon.com>
Cc:     Zhu Lingshan <lingshan.zhu@intel.com>, <jasowang@redhat.com>,
        <mst@redhat.com>, <alex.williamson@redhat.com>,
        <kvm@vger.kernel.org>, <linux-arm-kernel@lists.infradead.org>,
        <kvmarm@lists.cs.columbia.edu>, <cohuck@redhat.com>,
        <stable@vger.kernel.org>
Subject: Re: [PATCH] Revert "irqbypass: do not start cons/prod when failed connect"
In-Reply-To: <cfb68374-a7bf-1eb4-86cf-77c57f7fe9e5@hisilicon.com>
References: <20210508071152.722425-1-lingshan.zhu@intel.com>
        <8735uxvajh.wl-maz@kernel.org>
        <cfb68374-a7bf-1eb4-86cf-77c57f7fe9e5@hisilicon.com>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI-EPG/1.14.7 (Harue)
 FLIM-LB/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL-LB/10.8 EasyPG/1.0.0 Emacs/27.1
 (x86_64-pc-linux-gnu) MULE/6.0 (HANACHIRUSATO)
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
Content-Type: text/plain; charset=US-ASCII
X-SA-Exim-Connect-IP: 62.31.163.78
X-SA-Exim-Rcpt-To: zhangshaokun@hisilicon.com, lingshan.zhu@intel.com, jasowang@redhat.com, mst@redhat.com, alex.williamson@redhat.com, kvm@vger.kernel.org, linux-arm-kernel@lists.infradead.org, kvmarm@lists.cs.columbia.edu, cohuck@redhat.com, stable@vger.kernel.org
X-SA-Exim-Mail-From: maz@kernel.org
X-SA-Exim-Scanned: No (on disco-boy.misterjones.org); SAEximRunCond expanded to false
Precedence: bulk
List-ID: <stable.vger.kernel.org>
X-Mailing-List: stable@vger.kernel.org

On Mon, 10 May 2021 02:12:22 +0100,
Shaokun Zhang <zhangshaokun@hisilicon.com> wrote:
> 
> Hi Marc,
> 
> On 2021/5/8 17:29, Marc Zyngier wrote:
> > On Sat, 08 May 2021 08:11:52 +0100,
> > Zhu Lingshan <lingshan.zhu@intel.com> wrote:
> >>
> >> This reverts commit a979a6aa009f3c99689432e0cdb5402a4463fb88.
> >>
> >> The reverted commit may cause VM freeze on arm64 platform.
> >> Because on arm64 platform, stop a consumer will suspend the VM,
> >> the VM will freeze without a start consumer
> > 
> > It also unconditionally calls del_consumer on the producer, which
> > isn't exactly expected.
> > 
> >>
> >> Signed-off-by: Zhu Lingshan <lingshan.zhu@intel.com>
> > 
> > Reported-by: Shaokun Zhang <zhangshaokun@hisilicon.com>
> 
> Thanks for the tag, it works with this patch, So:
> Tested-by: Shaokun Zhang <zhangshaokun@hisilicon.com>
> 
> I shall invite you to have a drink for the quick debug.
> Anyway, thank you again.

No worries, glad we were able to root-cause the problem quickly
enough.

Thanks,

	M.

-- 
Without deviation from the norm, progress is not possible.
